# .travis.yml
 
language: php
 
php:
  - 7.1
 
script:
  # Run your tests here.
  - echo 'Tested'

branches:
  only:
  # Enable Travis hook on tags (it is regular expression for semver tag)*
  - "/\\d\\.\\d\\.\\d/"

# Enable Travis deployment
deploy:
  # Use script as a deployment tool
  provider: script
  script: deploy/deploy.sh
  # Restrict deployment only for tags
  on:
    tags: true